### PR TITLE
Correct faulty test for installation URLs.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
The existing check is too strict, leading to problems such as #21.

### CODE REVIEW

**Comment by heddn** [comment]
Are there ways I can test this?

**Comment by greg-1-anderson** [comment]
1. Create a new Drupal 8 site on Pantheon, but don't install it.
2. Clone the site, change the settings.php per this PR, and push the code back up, OR do the same operation in sftp mode.
3. Install your test site through the web installer.

**Comment by heddn** [comment]
I still received a redirect loop when selecting Espanol. Additionally, I noticed 
Allowed memory size of 268435456 bytes exhausted (tried to allocate 260046832 bytes)core/lib/Drupal/Core/Render/BareHtmlPageRenderer.php:70

Feel free to add yourself as a team member on http://dev-drops8.pantheon.io/ or PM me in IRC with your email address and I can add you.

**Comment by heddn** [comment]
Interesting, I got done pasting all above into a comment and returned to the chrome tab to close it. The redirect loop must have gone away, because it is now letting my continue the installation with Spanish. And now I cannot reproduce the redirect loop. Even by rolling back the commit. I tried rolling back the commit, then flushing cache. Still no success.

**Comment by greg-1-anderson** [comment]
The reason that the redirect loop is gone for your site is that this is a re-install; the test we have put in only catches and redirects to the installer on the initial install. Take a look at the dissatisfying third clause in the 'if' statement -- it detects whether this is an initial install by testing for the existence of the files/styles directory.  This does not exist on a clean site, but it does exist on a reinstall, so no redirect happens.

I think we should still commit this PR, because it is an improvement over the current workaround; however, I also think we should get rid of this part of our settings.php file completely per the alterations discussed in #3.

**Comment by greg-1-anderson** [comment]
Rolled in to #57.

**Pull request closed without merging**
