### PR TITLE
Fixes #111: Allow users to adjust services.yml

### LINKED ISSUE #111: Provide a way to persist the services.yml file outside SFTP mode
Users should not commit a sensitive services.yml file, but need it exist after switching to SFTP mode.
The file path is in .gitignore in the D8 core and in our upstream.

CASE: 49466

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Load 'services.pantheon.preproduction.yml' in dev and multidev environments, e.g. to turn on twig debugging.

### CODE REVIEW

**Comment by davidstrauss** [comment]
+1 on simply offering pre-production overrides. Not sure if we could be more clear what that means, as we should *not* apply such overrides in the test environment.

**Comment by greg-1-anderson** [comment]
@dts Reworded te comments in default.services.pantheon.preproduction.yml.

**Comment by greg-1-anderson** [comment]
Fixed in #159

**Comment by greg-1-anderson** [comment]
Deployed.

**Comment by dts** [comment]
Not sure which @dts you're mentioning, but I think it's safe to assume you're not talking about me 😃 .

**Comment by greg-1-anderson** [comment]
Sorry, @davidstrauss is @dts in our slack et. al. -- I have probably done this to you in the past. Will try to avoid in the future!  Thanks for the reminder.

**Comment by dts** [comment]
No worries!

**Pull request closed without merging**
