### PR TITLE
#37: Some pressflow things dont set drupal_hash_salt explicitly

### PR DESCRIPTION
**Pull request by pirog**
this is a better resolution to #37 until we can set this on the server side on KB2

### CODE REVIEW

**Comment by populist** [comment]
How about a clean swap to switch out checking for PRESSFLOW_SETTINGS and instead just check PANTHEON_ENVIRONMENT? Drupal will already make up a hash salt if it isn't set and no reason to duplicate that code.

/**
 * Handle Hash Salt Value from Drupal
 *
 * Issue: https://github.com/pantheon-systems/drops-8/issues/10
 *
 */
if (defined('PANTHEON_ENVIRONMENT')) {
  $settings['hash_salt'] = $drupal_hash_salt;
}

**Comment by pirog** [comment]
I don't think it will make up a hash salt if there is already a settings.php as is the case for drops 8?

**Comment by populist** [comment]
You are correct. Here is what you get without it:

```
RuntimeException: Missing $settings['hash_salt'] in settings.php. in Drupal\Core\Site\Settings::getHashSalt() (line 145 of /code/core/lib/Drupal/Core/Site/Settings.php).
```

**Comment by greg-1-anderson** [comment]
When I copy a Pantheon site down to my local system, I include `settings.local.php` from the last line of settings.php, and define the database values there.  In general, I don't think that you can expect $databases to be defined at the point where you sha256 it, which means that 'hash_salt' would then be more-or-less a constant for some folks.

This could be a security issue for anyone who ran drops-8 on a public non-Pantheon server.  Since the typical use-case for running drops-8 on a non-Pantheon site is to just make a private local copy for development, though, maybe this risk is acceptable, particularly since it is easy for the observant to fix.

Perhaps as a service, we should include `settings.local.php` just before calculating the hash salt.  That would give folks an easy place to define their databases record without modifying the default settings.php -- and as a bonus, hash_salt would then be calculated correctly for anyone who took that offer.

**Comment by populist** [comment]
In the case of this PR, I think it is safe to assume that $databases is present in cases where PRESSFLOW_SETTINGS is set since the logic immediately above defines it.

There are certainly going to be cases where people run this code on systems that don't define PRESSFLOW_SETTINGS (like everyone except for Pantheon or Kalabox) and in that case they would still need to manually define the hash_salt (and it will tell them that). 

+1 to including settings.local.php. There is another PR from MRF about it that we could merge at the same time.

**Comment by pirog** [comment]
+1 re pressflow settings being defined on kalabox

+1 to local settings as well


On Tuesday, May 26, 2015, Matt Cheney <notifications@github.com> wrote:

> In the case of this PR, I think it is safe to assume that $databases is
> present in cases where PRESSFLOW_SETTINGS is set since the logic
> immediately above defines it.
>
> There are certainly going to be cases where people run this code on
> systems that don't define PRESSFLOW_SETTINGS (like everyone except for
> Pantheon or Kalabox) and in that case they would still need to manually
> define the hash_salt (and it will tell them that).
>
> +1 to including settings.local.php. There is another PR from MRF about it
> that we could merge at the same time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/drops-8/pull/39#issuecomment-105701825>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
Also going to try for us to generate the hash salt in the ENV for KB2 soonish so this might ultimately be moot.

**Comment by pirog** [comment]
@populist @greg-1-anderson

We can get below to work on both pantheon on kalabox
```
$settings['hash_salt'] = getenv('DRUPAL_HASH_SALT');
```

Not sure if this is ideal in the pantheon context re: security but maybe @joshkoenig has suggestions on how to translate `getenv('DRUPAL_HASH_SALT');` to just `$drupal_hash_salt` on the server side. 

That would allow us to do this on both pantheon and kb2 with the current implementation.

**Comment by pirog** [comment]
whoop

just noticed
```
    else {
      $$key = $value;
    }
```
in the settings.php.

aka we can get kbox to use the same code. will update our plugins to do this and then close this pr.

**Comment by greg-1-anderson** [comment]
Per the [above comment](https://github.com/pantheon-systems/drops-8/pull/39#issuecomment-106661233), is this solved on the Kalabox side now? Can we go ahead and close this PR?

**Comment by davidstrauss** [comment]
I saw SHA-256 mentioned, and I just wanted to push for SHA-512 instead, if a decision is being made related to this. SHA-512 is substantially faster on modern 64-bit processors. SHA-256 is only faster on 32-bit systems.

**Comment by greg-1-anderson** [comment]
So we essentially just used the environment variable settings (as suggested above)[https://github.com/pantheon-systems/drops-8/pull/39#issuecomment-106164484] in #57.

**Pull request closed without merging**
