### PR TITLE
[CORE-1355] Enforce HTTPS by default.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Enforce HTTPS. For more info see https://pantheon.io/blog/pantheon-now-enforces-https-default-plus-really-simple-hsts

Create your own test site to verify:

  - Create a new Drupal 8 site on Pantheon.
  - When site creation is finished, visit dashboard.
  - Switch to "git" mode.
  - Clone your site locally.
  - Apply the files from this PR on top of your local checkout.
    - git remote add drops-8 git@github.com:pantheon-systems/drops-8.git
    - git fetch drops-8
    - git merge drops-8/https-by-default
  - Push your files back up to Pantheon.
  - Switch back to sftp mode.
  - Visit your site and step through the installation process.

### CODE REVIEW

**Comment by ataylorme** [comment]
@greg-1-anderson my only concern here is that setting the HSTS header is making a promise the site will always be HTTPS and making that decision should be left to users because they can choose to remove HTTPS in the future.

Aside from that, I think we should like to documentation and not a blog post. Maybe https://pantheon.io/docs/pantheon-yml/?

**Comment by mbaynton** [comment]
+1
New site with PR applied installs fine
HTTPS redirect and hsts header occur.

@ataylorme 

> setting the HSTS header is making a promise the site will always be HTTPS

No, we'll be okay here. We promise it will be HTTPS for the next 300 seconds :)

**Comment by greg-1-anderson** [comment]
@ataylorme `transitional` means that the https promise only lasts for five minutes, and does not include subdomains. The user may choose to customize these settings in their `pantheon.yml` before they deploy their updated site to production.

Documentation in support of this change:

- https://github.com/pantheon-systems/documentation/pull/5164
- https://github.com/pantheon-systems/documentation/pull/5168

The theoretical schedule for this change is:

- Make blog readable 9am ~ 9:30am
- Merge this PR 9:30am ~ 10am
- Social media promotion et. al 11am

**Comment by ataylorme** [comment]
> `transitional` means that the https promise only lasts for five minutes, and does not include subdomains

👍 that works! Maybe we should add a code comment in the `pantheon.yml` to that effect and link to the docs? That way folks know they have more options and that we recommend `full` or `full+subdomains` if they are comfortable with the longer header length.

**Comment by ataylorme** [comment]
@greg-1-anderson will there be a similar PR for WordPress?

**Comment by greg-1-anderson** [comment]
Yeah I still need to do WordPress and Drupal 7.

For the comment, we currently have:

> See https://pantheon.io/docs/pantheon-yml/#enforce-https--hsts for valid values.

So, there is a link to the docs, but it does not explicitly say what the effect of transitional is. Perhaps this will encourage folks to click through and find out all of the details. 😄

**Pull request merged**
