### PR TITLE
[CMS-147] + [PRT-227] Update to PHP 7.4 and MariaDB 10.4

### PR DESCRIPTION
**Pull request by greg-1-anderson**
For details, see https://pantheon.io/docs/pantheon-yml#specify-a-version-of-mariadb

See also pantheon-systems/documentation#6928, which modifies that section.

### CODE REVIEW

**Comment by Hornswoggles** [comment]
+1

**Review by CdrMarks — CHANGES_REQUESTED** [review]
I'm +1 to the PHP/Maria change.

The Circle CI test has a merge conflict.

**Comment by greg-1-anderson** [comment]
Yeah I have to either merge my test change into the default branch, or just back it out and merge this with failing tests.

**Comment by greg-1-anderson** [comment]
I force-pushed the test changes from this branch onto the default branch, which took care of the merge conflict here.

If we want to get rid of these test modifications later, we could cherry-pick 9e9928a3b onto default later (after hard-reseting default to get rid of the "CircleCI 2.0 tests" commit that's there right now).

**Pull request merged**
