### PR TITLE
Update to Drupal 8.0.1.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
For more information, see https://www.drupal.org/node/2627402

Instructions to test:

- Create a new Drupal 8 site on Pantheon.
- When site creation is finished, visit dashboard.
- Switch to "git" mode.
- Clone your site locally.
- Apply the files from this PR on top of your local checkout.
  - git remote add drops-8 git@github.com:pantheon-systems/drops-8.git
  - git fetch drops-8
  - git merge drops-8/update-8.0.1
- Push your files back up to Pantheon.
- Switch back to sftp mode.
- Visit your site. Step through the installation process. Look for any problems.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Seems to be working okay.

**Comment by fujin** [comment]
lgtm :+1: ? the diff is pretty ridiculous/impossible to review. assuming has been tested :green_apple:

**Comment by greg-1-anderson** [comment]
True, it is pointless to try to review the diffs in these releases, since so many commits go into even minor Drupal updates, and it would be impossible / pointless to validate whether the commits made by the community are appropriate.

**Comment by craychee** [comment]
@greg-1-anderson :+1: walked through the installation and update process with problems.

**Comment by greg-1-anderson** [comment]
@craychee: **with** problems, or **without** problems?  :)

**Comment by craychee** [comment]
@greg-1-anderson *no* problems.

**Comment by greg-1-anderson** [comment]
Heave ho, and away we go, then!

**Pull request merged**
