### PR TITLE
Drupal 8.0.0 beta12

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Update to Drupal 8.0.0 beta 12, by merging in the d8b12 commits into the Pantheon d8b11.

Still testing.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Instructions to test:

1. Create a new Drupal 8 site on Pantheon via https://dashboard.pantheon.io/products/drupal8/spinup.
2. When site creation is finished, **do not visit site**; instead, visit dashboard.
3. Switch to "git" mode, throwing away the unchanged commit.
4. Clone your site locally.
5. Apply the files from this PR on top of your local checkout.
6. Push your files back up to Pantheon.
7. **Switch back to sftp mode**.
8. Visit your site.  Step through the installation process.

Steps 3 and 8 are very important.

**Comment by greg-1-anderson** [comment]
This should be combined with #43 before being merged to master.

**Comment by greg-1-anderson** [comment]
The commit above for #43 installs fine.  Ready for review again.

**Comment by populist** [comment]
+1 from me. i created a new site + updated an old one.

**Comment by darol100** [comment]
This works for me. However, when I switch back to SFTP I had to commit the changes for some reason. Otherwise it would not let me to continue the installation.

**Comment by greg-1-anderson** [comment]
Updating an older version of Drupal 8 to beta 12 is not supported -- but you can always try it, and do a happy dance if it works.  Updates from beta 12 to following releases will be supported.

Now that this PR has been merged in, along with the fix to #43, it is no longer necessary to be concerned about throwing out the 'files' directory creation, as it is now safely excluded by the .gitignore file.

**Pull request closed without merging**
