### PR TITLE
Update to drupal 8.0.0-beta16. 

### PR DESCRIPTION
**Pull request by greg-1-anderson**
For more information, see https://www.drupal.org/node/2578775

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
This patch is not correct -- I will push the fixed branch here later.

**Comment by greg-1-anderson** [comment]
On Pantheon, I get:
```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 258474155 bytes) in /srv/bindings/3ba1271803484bebad322bc08c5d11bf/code/vendor/twig/twig/lib/Twig/Environment.php on line 265
```
Locally, I have seen a similar failure on the same line:
```
Fatal error: Class 'Twig_Cache_Null' not found in /Users/ga/pantheon/drupal/d8b16-take3/vendor/twig/twig/lib/Twig/Environment.php on line 265
```
There wouldn't happen to be any sort of class-not-found error handler inserted on the Pantheon platform, would there?  If Pantheon sometimes converted class-not-found errors into out-of-memory errors, then this could be related to #54.

Still trying to figure out the cause of the class-not-found error on my local system. Have not traced it down yet.

**Comment by greg-1-anderson** [comment]
The `Twig_Cache_Null` error mentioned above was caused by some missing directories named 'Cache' that are committed in the Drupal repository on drupal.org, but that did not make it into drops-8 due to our .gitignore file.  This PR is now working fine, as of the last force-push.

**Comment by greg-1-anderson** [comment]
Looking for a +1.  Instructions to test:

1. Create a new Drupal 8 site on Pantheon via https://dashboard.pantheon.io/products/drupal8/spinup.
2. When site creation is finished, **do not visit site**; instead, visit dashboard.
3. Switch to "git" mode.
4. Clone your site locally.
5. Apply the files from this PR on top of your local checkout. Also test with #86 and #87.
 - git remote add drops-8 git@github.com:pantheon-systems/drops-8.git
 - git fetch drops-8
 - git merge 8.0.0-beta16
 - git merge remove-active
 - git merge relocate-staging
6. Push your files back up to Pantheon.
7. **Switch back to sftp mode**.
8. Visit your site.  Step through the installation process.

Steps 3 and 7 are important.

Look for any regressions.

 - Schrodinger's cache: "Can not find module `standard`, during site install, on the status report page, on the configuration sync admin page, etc.
 - Problems with redirect to core/install.php (going there when you shouldn't, not going there when you should, etc.)
 - Problems installing in other languages
 - Problems creating the test environment
 - etc.

**Comment by bmackinney** [comment]
@greg-1-anderson I followed steps 1-8 successfully. 
I then tried to install a module and recieved the error noted in https://github.com/pantheon-cookbooks/drush/issues/11.  
I wiped the change to `sites/default/settings.php` and the db and hit dev again. It directed me to install.php. I  installed again, in Spanish. `sites/default/settings.php` was modified successfully and the site installed correctly. 
I then created the Test Environment, it succeeded.

**Comment by bmackinney** [comment]
I forgot to mention that downloading a module via the UI failed as well: 
```site
Installing devel
An error has occurred. 
Please continue to the wrong page

There was an AJAX HTTP error.
HTTP Result Code: 404
Then the detailed debugging information.
Route: /core/authorize.php/core/authorize.php?batch=1&id=4&op=do_nojs&op=do
StatusText: Not Found
ResponseText: {"message": "No route found for \ u0022POST \ / core \ /authorize.php \ / core \ /authorize.php \ u0022 (from \u0022http:\/\/dev-book-blog.pantheon.io\/core\/authorize.php?batch=1\u0026id=4\u0026op=start\u0022)"}```

**Comment by greg-1-anderson** [comment]
The module install thing is an issue on 8.0.0-beta15 also.

**Comment by HongPong** [comment]
Well a little good news, time to put RC1 on there! It's still set on beta as of now (and that launch signup page language should change to RC from beta too)

**Comment by wizonesolutions** [comment]
+1

**Comment by greg-1-anderson** [comment]
Yes, working on one more platform issue that I wanted to get in for beta16.  Looks like we'll be going straight to RC1 now, and yes, we'll need to change the language on the landing page at some point.

**Comment by greg-1-anderson** [comment]
We're not going to roll out beta16 on Pantheon -- closing. RC1 should be available soon.

**Comment by tormi** [comment]
+1

**Comment by greg-1-anderson** [comment]
Also, I confirmed that the `/core/authorize.php/core/authorize.php` bug exists in Drupal 8.0.0-rc1. Could not find anything in the issue queue for it, so created https://www.drupal.org/node/2583799

**Pull request closed without merging**
