### PR TITLE
removes icon ignore

### PR DESCRIPTION
**Pull request by ryanschmidt**
This rule creates issues on both Drupal and Wordpress installs. Instead of only excluding OS files (as the .gitignore comment implies) it ignores any folder titled "icon" or "icons" found in various module folders.

### CODE REVIEW

**Comment by mparker17** [comment]
macOS does create an `Icon\r` (where `\r` is the 0x0D carriage return symbol) file for some reason; Github's official gitignore repo's file for macOS encodes that \r directly to avoid confusion with "icon" or "Icons" folders: https://github.com/github/gitignore/blob/master/Global/macOS.gitignore#L7

**Comment by woodseowl** [comment]
I found this PR right after I added issue #271. See that issue for details. In short: the "Icon" should be there but is supposed to have newlines with it and in commit ac79554 they appear to have been lost due to line ending conversion, resulting in the "Icon?".

**Comment by ryanschmidt** [comment]
@woodseowl great find! Closing this in favor of https://github.com/pantheon-systems/drops-8/issues/271

**Comment by woodseowl** [comment]
Thanks, @ryanschmidt! Hopefully @greg-1-anderson can pick up #271 before the next Drupal release ;)

**Pull request closed without merging**
